[package]
name = "servo-media-gstreamer-render-macos"
version = "0.1.0"
authors = ["The Servo Project Developers"]

[lib]
name = "servo_media_gstreamer_render_macos"
path = "lib.rs"

[dependencies.servo-media-gstgl-macos-bindings]
path = "bindings"
