[package]
name = "servo-media-gstreamer-render-unix"
version = "0.1.0"
authors = ["The Servo Project Developers"]

[lib]
name = "servo_media_gstreamer_render_unix"
path = "lib.rs"

[dependencies.gstreamer]
version = "0.14"

[dependencies.gstreamer-gl]
version = "0.14"
features = ["egl"]

[dependencies.gstreamer-video]
version = "0.14"

[dependencies.servo-media-player]
path = "../../../player"

[dependencies.servo-media-gstreamer-render]
path = "../render"
