[package]
name = "servo-media-gstreamer"
version = "0.1.0"
authors = ["The Servo Project Developers"]

[build-dependencies]
regex = "1.0"
zip = "0.3.1"
lazy_static = "1.2.0"

[dependencies]
boxfnonce = "0.1.0"

[dependencies.byte-slice-cast]
version = "0.2"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"

[dependencies.gstreamer-sys]
git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs-sys"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"

[dependencies.gstreamer]
git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"
features = ["subclassing"]

[dependencies.gstreamer-app]
git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"

[dependencies.gstreamer-audio]
git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"

[dependencies.gstreamer-player]
git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"

[dependencies.gstreamer-sdp]
git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"

[dependencies.gstreamer-webrtc]
git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"

[dependencies.gstreamer-video]
git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"

[dependencies.ipc-channel]
version = "0.11"

[dependencies.lazy_static]
version = "1.2.0"

[dependencies.servo-media-audio]
path = "../../audio"

[dependencies.servo-media-player]
path = "../../player"

[dependencies.url]
version = "1.7.2"

[dependencies.servo-media-webrtc]
path = "../../webrtc"
