[package]
name = "servo-media-gstreamer"
version = "0.1.0"
authors = ["The Servo Project Developers"]

[build-dependencies]
regex = "1.0"
zip = "0.3.1"
lazy_static = "1.0"

[dependencies]
boxfnonce = "0.1.0"

[dependencies.byte-slice-cast]
version = "0.2"

[dependencies.glib]
version = "0.7"

[dependencies.glib-sys]
version = "0.8"

[dependencies.gstreamer-sys]
version = "0.7"

[dependencies.gstreamer-sdp-sys]
version = "0.7"

[dependencies.gstreamer]
version = "0.13"
features = ["subclassing"]

[dependencies.gstreamer-app]
version = "0.13"

[dependencies.gstreamer-audio]
version = "0.13"

[dependencies.gstreamer-player]
version = "0.13"

[dependencies.gstreamer-sdp]
version = "0.13"

[dependencies.gstreamer-webrtc]
version = "0.13"

[dependencies.gstreamer-video]
version = "0.13"

[target.'cfg(not(target_os = "linux"))'.dependencies]
gstreamer-gl = { path = "../gstreamer-gl" }

[target.'cfg(target_os = "linux")'.dependencies]
gstreamer-gl-egl = { path = "../gstreamer-gl-egl" }

[dependencies.ipc-channel]
version = "0.11"

[dependencies.lazy_static]
version = "1.2.0"

[dependencies.servo-media]
path = "../../servo-media"

[dependencies.servo-media-audio]
path = "../../audio"

[dependencies.servo-media-player]
path = "../../player"

[dependencies.url]
version = "1.7.2"

[dependencies.servo-media-streams]
path = "../../streams"

[dependencies.servo-media-webrtc]
path = "../../webrtc"
