[package]
name = "servo-media"
version = "0.1.0"
authors = ["Manish Goregaokar <manishsmail@gmail.com>"]

[lib]
name = "servo_media"

[dependencies.servo-media-audio]
path = "../audio"

[dependencies.servo-media-player]
path = "../player"

[target.'cfg(all(not(target_os = "android"), not(target_os = "window"), target_arch = "x86_64"))'.dependencies.servo-media-gstreamer]
path = "../backends/gstreamer"
